const base = {
  IsSuccess: true,
  Message: null,
};

export const list = {
  HasFolder: true,
  FolderExist: true,
  Headers: [
    {
      InternalName: 'DocIcon',
      DisplayName: 'Type',
      Type: 'Computed',
    },
    {
      InternalName: 'LinkFilename',
      DisplayName: 'Name',
      Type: 'Computed',
    },
    {
      InternalName: 'Modified',
      DisplayName: 'Modified',
      Type: 'DateTime',
    },
    {
      InternalName: 'Editor',
      DisplayName: 'Modified By',
      Type: 'User',
    },
    {
      InternalName: 'Viewing_x0020_rights',
      DisplayName: 'Viewing rights',
      Type: 'MultiChoice',
    },
    {
      InternalName: 'Published',
      DisplayName: 'Published',
      Type: 'Boolean',
    },
    {
      InternalName: 'Created',
      DisplayName: 'Created',
      Type: 'DateTime',
    },
    {
      InternalName: 'Author',
      DisplayName: 'Created By',
      Type: 'User',
    },
    {
      InternalName: 'FileSizeDisplay',
      DisplayName: 'File Size',
      Type: 'Computed',
    },
    {
      InternalName: 'Information_x0020_Group',
      DisplayName: 'Information Group',
      Type: 'MultiChoice',
    },
    {
      InternalName: 'Service_x002f_Process',
      DisplayName: 'Service/Process',
      Type: 'MultiChoice',
    },
  ],
  IsSuccess: true,
  Message: null,
  Folder: {
    Id: '06c8a81e-453d-47b6-89df-93128df8f71e',
    Name: '53820cfc-8e4a-e711-8106-005056ac126a',
    Url: 'https://performance.premis.fi/fiscalyears/53820cfc-8e4a-e711-8106-005056ac126a',
    Folders: [
      {
        Id: 'ac769be4-efbd-4ef9-ae95-919e46b88700',
        Name: 'CREATE_UPDATE',
        Url: 'https://performance.premis.fi/fiscalyears/53820cfc-8e4a-e711-8106-005056ac126a/CREATE_UPDATE',
        Folders: [
          {
            Id: 'b27783e7-2575-4a41-97b0-59e973160d22',
            Name: 'Folder 11',
            Url: 'https://performance.premis.fi/fiscalyears/53820cfc-8e4a-e711-8106-005056ac126a/CREATE_UPDATE/Folder 11',
            Folders: [],
            Documents: [
              {
                Id: '09028456-2725-45e8-af1e-c99062033076',
                Name: 'Meeting agenda (56).pdf',
                Values: {
                  DocIcon: 'pdf',
                  LinkFilename: 'Meeting agenda (56).pdf',
                  Modified: '15.11.2021 14:02:02',
                  Editor: 'System Account',
                  Viewing_x0020_rights: 'Isännöitsijä, Kirjanpitäjä, Hallitus',
                  Published: 'False',
                  Created: '15.11.2021 14:02:00',
                  Author: 'System Account',
                  FileSizeDisplay: '12398',
                  Information_x0020_Group: 'Tilinpäätös',
                  Service_x002f_Process: 'Talous',
                },
                Size: 12398,
              },
            ],
            Values: {
              DocIcon: '',
              LinkFilename: 'Folder 11',
              Modified: '17.11.2021 17:14:12',
              Editor: 'System Account',
              Viewing_x0020_rights: '',
              Published: '',
              Created: '4.11.2021 9:24:17',
              Author: 'm.mishko@premis.local',
              FileSizeDisplay: '',
              Information_x0020_Group: '',
              Service_x002f_Process: '',
            },
          },
          {
            Id: 'ab7b876d-308d-4b3c-a251-429d67b976e2',
            Name: 'Folder 12',
            Url: 'https://performance.premis.fi/fiscalyears/53820cfc-8e4a-e711-8106-005056ac126a/CREATE_UPDATE/Folder 12',
            Folders: [],
            Documents: [
              {
                Id: '40df0b4e-c60c-4fa3-b56a-b8ba0d1b74f1',
                Name: 'logo-tahkola-png-to-svg.svg',
                Values: {
                  DocIcon: 'svg',
                  LinkFilename: 'logo-tahkola-png-to-svg.svg',
                  Modified: '12.11.2021 19:11:18',
                  Editor: 'System Account',
                  Viewing_x0020_rights: 'Isännöitsijä, Kirjanpitäjä, Hallitus',
                  Published: 'False',
                  Created: '12.11.2021 19:11:18',
                  Author: 'System Account',
                  FileSizeDisplay: '6034',
                  Information_x0020_Group: '',
                  Service_x002f_Process: '',
                },
                Size: 6034,
              },
            ],
            Values: {
              DocIcon: '',
              LinkFilename: 'Folder 12',
              Modified: '12.11.2021 11:12:32',
              Editor: 'System Account',
              Viewing_x0020_rights: '',
              Published: '',
              Created: '4.11.2021 9:24:23',
              Author: 'm.mishko@premis.local',
              FileSizeDisplay: '',
              Information_x0020_Group: '',
              Service_x002f_Process: '',
            },
          },
        ],
        Documents: [],
        Values: {
          DocIcon: '',
          LinkFilename: 'CREATE_UPDATE',
          Modified: '5.11.2021 1:35:32',
          Editor: 'System Account',
          Viewing_x0020_rights: '',
          Published: '',
          Created: '4.11.2021 9:23:50',
          Author: 'm.mishko@premis.local',
          FileSizeDisplay: '',
          Information_x0020_Group: '',
          Service_x002f_Process: '',
        },
      },
      {
        Id: '8bb4d830-0de1-44d3-a4a0-0e09aac9b842',
        Name: 'Folder 3',
        Url: 'https://performance.premis.fi/fiscalyears/53820cfc-8e4a-e711-8106-005056ac126a/Folder 3',
        Folders: [
          {
            Id: '4c83d63f-0b73-4351-b277-735ca92e1c6e',
            Name: 'qq',
            Url: 'https://performance.premis.fi/fiscalyears/53820cfc-8e4a-e711-8106-005056ac126a/Folder 3/qq',
            Folders: [],
            Documents: [],
            Values: {
              DocIcon: '',
              LinkFilename: 'qq',
              Modified: '12.11.2021 17:30:37',
              Editor: 'System Account',
              Viewing_x0020_rights: '',
              Published: '',
              Created: '12.11.2021 17:30:37',
              Author: 'System Account',
              FileSizeDisplay: '',
              Information_x0020_Group: '',
              Service_x002f_Process: '',
            },
          },
        ],
        Documents: [],
        Values: {
          DocIcon: '',
          LinkFilename: 'Folder 3',
          Modified: '4.11.2021 9:24:09',
          Editor: 'm.mishko@premis.local',
          Viewing_x0020_rights: '',
          Published: '',
          Created: '4.11.2021 9:24:09',
          Author: 'm.mishko@premis.local',
          FileSizeDisplay: '',
          Information_x0020_Group: '',
          Service_x002f_Process: '',
        },
      },
    ],
    Documents: [
      {
        Id: 'a571b4e0-e63d-431f-b0fb-20bc59fcfdd4',
        Name: 'Meeting agenda (56).pdf',
        Values: {
          DocIcon: 'pdf',
          LinkFilename: 'Meeting agenda (56).pdf',
          Modified: '4.11.2021 21:30:34',
          Editor: 'System Account',
          Viewing_x0020_rights: '',
          Published: 'True',
          Created: '4.11.2021 9:25:51',
          Author: 'm.mishko@premis.local',
          FileSizeDisplay: '12398',
          Information_x0020_Group: '',
          Service_x002f_Process: '',
        },
        Size: 12398,
      },
      {
        Id: 'c2fb0e0b-a8e4-454c-9d74-4a4b08d9ad98',
        Name: 'ErrorDetails.txt',
        Values: {
          DocIcon: 'txt',
          LinkFilename: 'ErrorDetails.txt',
          Modified: '17.11.2021 18:13:23',
          Editor: 'System Account',
          Viewing_x0020_rights: 'Isännöitsijä, Kirjanpitäjä, Hallitus',
          Published: 'False',
          Created: '17.11.2021 18:13:22',
          Author: 'System Account',
          FileSizeDisplay: '2123',
          Information_x0020_Group: 'Tilinpäätös, Talousarvio, Lasku, Raportti',
          Service_x002f_Process: 'Talous, Hallinto, Tekniset asiat',
        },
        Size: 2123,
      },
    ],
    Values: {
      DocIcon: '',
      LinkFilename: '53820cfc-8e4a-e711-8106-005056ac126a',
      Modified: '4.11.2021 9:21:06',
      Editor: 'System Account',
      Viewing_x0020_rights: '',
      Published: '',
      Created: '4.11.2021 9:21:06',
      Author: 'System Account',
      FileSizeDisplay: '',
      Information_x0020_Group: '',
      Service_x002f_Process: '',
    },
  },
};

export const attr = {
  Attributes: [
    {
      AvailableValues: [
        'Isännöitsijä',
        'Kirjanpitäjä',
        'Hallitus',
        'Osakas',
        'Asukas',
        'Huoltoyhtiö',
        'Rakennuttajan asiamies',
        'Takuuvastaava',
        'Urakoitsija',
        'Valvoja',
      ],
      Type: 0,
      TypeString: 'MultiChoise',
      DisplayName: 'Viewing rights',
      InternalName: 'Viewing_x0020_rights',
    },
    {
      AvailableValues: [
        'Pöytäkirja',
        'Tilinpäätös',
        'Talousarvio',
        'Raportti',
        'Lasku',
        'Sopimus',
        'Vero',
        'Suunnitelma',
        'Piirustus',
        'Säännöt',
        'Tiedote',
        'Vakuutus',
        'Muut',
      ],
      Type: 0,
      TypeString: 'MultiChoise',
      DisplayName: 'Information Group',
      InternalName: 'Information_x0020_Group',
    },
    {
      AvailableValues: [
        'Hallinto',
        'Talous',
        'Tekniset asiat',
        'Käyttö ja ylläpito',
        'Muut',
      ],
      Type: 0,
      TypeString: 'MultiChoise',
      DisplayName: 'Service/Process',
      InternalName: 'Service_x002f_Process',
    },
  ],
  IsSuccess: true,
  Message: null,
};

export const baseCooperatives = {
  ...base,
  Cooperatives: [
    {
      Id: 'a98ee91c-e3ea-e711-8105-005056ac5819',
      Name: 'As Oy Demotalo',
      LatesClosedDate: '2017-12-31T01:00:00Z',
      IsOwn: true,
      IsPMCompanyEmployee: false,
    },
  ],
};

export const enhancedCooperatives = {
  ...base,
  Cooperatives: [
    {
      Id: 'a98ee91c-e3ea-e711-8105-005056ac5819',
      Name: 'As Oy Demotalo',
      LatesClosedDate: '2017-12-31T01:00:00Z',
      IsFinancialCalculationsAccepted: false,
      FiscalYearId: 'efb34799-2836-eb11-8110-005056ac71e1',
      IsFiscalYearClosed: false,
      FiscalYearStartDate: '2020-12-31T22:00:00Z',
      FiscalYearEndDate: '2021-12-30T22:00:00Z',
      BoardMeetingPlannedDate: null,
      BoardMeetingActualDate: null,
      GeneralMeetingPlannedDate: null,
      GeneralMeetingActualDate: null,
      AuditingPlannedDate: null,
      AuditingActualDate: null,
      Comments: null,
    },
  ],
};
